/**
 * Treasury Wallet Loader
 * Loads the treasury wallet from treasury.json (generated by initSolana.js)
 * Falls back to SOLANA_PRIVATE_KEY from environment if treasury.json doesn't exist
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { Keypair } from "@solana/web3.js";
import bs58 from "bs58";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const TREASURY_FILE = path.resolve(__dirname, "../treasury.json");

/**
 * Load the treasury wallet (the wallet that mints coins to players)
 * @returns {Keypair} The treasury wallet keypair
 * @throws {Error} If neither treasury.json nor SOLANA_PRIVATE_KEY is available
 */
let cachedWallet = null;

export function loadTreasuryWallet() {
  // Return cached wallet if already loaded
  if (cachedWallet) {
    return cachedWallet;
  }

  // First, try to load from treasury.json (dev wallet)
  if (fs.existsSync(TREASURY_FILE)) {
    try {
      const treasuryData = JSON.parse(fs.readFileSync(TREASURY_FILE, "utf8"));
      
      if (!treasuryData.secretKey) {
        throw new Error("treasury.json missing secretKey field");
      }
      
      const secretKey = bs58.decode(treasuryData.secretKey);
      const treasuryWallet = Keypair.fromSecretKey(secretKey);
      
      // Cache the wallet
      cachedWallet = treasuryWallet;
      
      // Only log once on first load
      if (!process.env.SUPPRESS_TREASURY_LOG) {
        console.log(`✅ Using Treasury Wallet: ${treasuryWallet.publicKey.toString()}`);
      }
      
      return treasuryWallet;
    } catch (error) {
      console.warn(`⚠️  Failed to load treasury.json: ${error.message}`);
    }
  }

  // Fallback to SOLANA_PRIVATE_KEY from environment
  const SOLANA_PRIVATE_KEY = process.env.SOLANA_PRIVATE_KEY;
  if (SOLANA_PRIVATE_KEY) {
    try {
      const adminSecretKey = bs58.decode(SOLANA_PRIVATE_KEY);
      const adminWallet = Keypair.fromSecretKey(adminSecretKey);
      
      // Cache the wallet
      cachedWallet = adminWallet;
      
      // Only log once on first load
      if (!process.env.SUPPRESS_TREASURY_LOG) {
        console.log(`✅ Using SOLANA_PRIVATE_KEY from .env: ${adminWallet.publicKey.toString()}`);
      }
      
      return adminWallet;
    } catch (error) {
      throw new Error(`Failed to decode SOLANA_PRIVATE_KEY: ${error.message}`);
    }
  }

  throw new Error(
    "Treasury wallet not found. Run 'npm run init-solana' to generate treasury.json, or set SOLANA_PRIVATE_KEY in .env"
  );
}
